services:
  gwdb:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_secrets
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_secrets
    secrets:
      - db_secrets

  wp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - gwdb
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      WORDPRESS_DB_HOST: gwdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_secrets
    secrets:
      - db_secrets

secrets:
  db_secrets:
    file: ./.env

volumes:
  db_data:
